nginx:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - "phpfpm"
  volumes:
    - /home/compose-lnmp/www/:/var/www/html/
    - /home/compose-lnmp/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
phpfpm:
  build: ./phpfpm
  ports:
    - "9000:9000"
  volumes:
    - ./www/:/var/www/html/
    - /home/compose-lnmp/phpfpm/conf/:/usr/local/etc/php/
  links:
    - "mysql"
mysql:
  build: ./mysql
  ports:
    - "63751:3306"
  volumes:
    - /home/compose-lnmp/mysql/data/:/var/lib/mysql/
  environment:
    MYSQL_ROOT_PASSWORD : wsjg123!@#